# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8
language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
- gem uninstall --all --executables cocoapods
- gem install cocoapods --version 1.1.0.rc.2 --no-document
script:
- set -o pipefail && xcodebuild test -workspace Example/Strongbox.xcworkspace -scheme Strongbox-Example -sdk iphonesimulator10.0 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
